# Use the official pgAdmin image as the base image
FROM dpage/pgadmin4:latest

# Set custom environment variables (optional)
ENV PGADMIN_DEFAULT_EMAIL=Manoranjan@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=Manoranjan

# Optionally, you can copy custom configuration files
# COPY ./pgadmin_config.py /pgadmin4/config_local.py

# Expose the pgAdmin web UI port
EXPOSE 80
